FROM node:10.13.0 as builder
ARG azure_user
ARG azure_pwd
ARG azure_site
COPY . /app
WORKDIR /app
RUN yarn && yarn run build
RUN cp .deployment dist
RUN cp deploy.sh dist
WORKDIR /app/dist
# No package restore on azure anymore, push them all via git
RUN yarn install --production
RUN git init
RUN git config user.email "deploy@docker" && git config user.name "deploy from docker"
RUN git add . && git commit -m "deploy" && git push -f "https://${azure_user}:${azure_pwd}@${azure_site}.scm.azurewebsites.net:443/${azure_site}.git" HEAD:master
RUN rm -rf .git/

FROM node:10.13.0-alpine
COPY --from=builder /app/dist/ /app
WORKDIR /app
EXPOSE 8080
CMD yarn start
